name: "Manual - Test Features"
on:
  workflow_dispatch:
    inputs:
      features:
        description: "List of feature to execute tests against"
        required: true
        default: "mold-linker"
      baseImage:
        description: "Base image"
        required: true
        default: "debian:bookworm"
      logLevel:
        description: "Log level (info/debug/trace)"
        required: true
        default: "info"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing '${{ github.event.inputs.features }}' against '${{ github.event.inputs.baseImage }}'"
        run: devcontainer features test --features ${{ github.event.inputs.features }} --base-image ${{ github.event.inputs.baseImage }} --log-level ${{ github.event.inputs.logLevel }} .
